### ISSUE TITLE
eth2 sync error: Receipt not available for 'From' block '11052984'

### ISSUE THREAD

**Issue by shayanb** [rocket-pool/smartnode#345]
I recently used smartnode to bootstrap a node (with checkpoint sync) and it is still syncing (although I only see 99.99% on eth1 for the last day when I check with `rocketpool node sync`.

```
Your primary execution client is still syncing (99.99%).
You do not have a fallback execution client enabled.
Your primary consensus client is fully synced.
You do not have a fallback consensus client enabled.
```

when I look up eth2 logs, I've been seeing this error almost since the early hour of the sync process, thought it will be resolved once eth1 is synced, however it is still ongoing and I wonder if this is the reason the sync is not finishing, but I might be wrong. 

Here's the error I get on eth2 container logs (lodestar):
```bash
rocketpool_eth2  | Apr-11 16:31:17.000[]                 info: Synced - slot: 6200554 - head: 6200554 0x639f…6055 - execution: syncing(0x0556…6e79) - finalized: 0x49d1…99ba:193765 - peers: 20
rocketpool_eth2  | Apr-11 16:31:17.553[eth1]            error: Error updating eth1 chain cache  JSON RPC error: Receipt not available for 'From' block '11052984'., eth_getLogs
rocketpool_eth2  | Error: JSON RPC error: Receipt not available for 'From' block '11052984'., eth_getLogs
rocketpool_eth2  |     at parseRpcResponse (file:///usr/app/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:273:11)
rocketpool_eth2  |     at JsonRpcHttpClient.fetch (file:///usr/app/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:111:12)
rocketpool_eth2  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
rocketpool_eth2  |     at Eth1Provider.getLogs (file:///usr/app/packages/beacon-node/src/eth1/provider/eth1Provider.ts:149:21)
rocketpool_eth2  |     at Eth1Provider.getDepositEvents (file:///usr/app/packages/beacon-node/src/eth1/provider/eth1Provider.ts:79:24)
rocketpool_eth2  |     at Eth1DepositDataTracker.updateDepositCache (file:///usr/app/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:225:23)
rocketpool_eth2  |     at Eth1DepositDataTracker.update (file:///usr/app/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:207:33)
rocketpool_eth2  |     at Eth1DepositDataTracker.runAutoUpdate (file:///usr/app/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:170:29)
```
It's been the exact same error on the same block since it started `Receipt not available for 'From' block '11052984'` .

Any ideas what this issue is caused by? I report back if/when the sync finishes.

**Comment by 0xfornax** [comment]
Closing as this was due to the clients and not the Smart Node.
