### ISSUE TITLE
[bug] Node crashes when fallback clients need to be used

### ISSUE THREAD

**Issue by alekscp** [rocket-pool/smartnode#399]
Running in native mode
smartnode `1.10.2`

I stopped my execution client in order to perform pruning (`geth`). The fallback EC and EE were synced and responding. The node was reporting connecting to the fallback clients but kept crashing.

```bash
...
Oct 29 08:29:51 ethpower systemd[1]: rp-node.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 29 08:29:51 ethpower systemd[1]: rp-node.service: Failed with result 'exit-code'.
Oct 29 08:29:56 ethpower systemd[1]: rp-node.service: Scheduled restart job, restart counter is at 9.
Oct 29 08:29:56 ethpower systemd[1]: Stopped rp-node.
Oct 29 08:29:57 ethpower systemd[1]: Started rp-node.
Oct 29 08:29:58 ethpower rocketpoold[39569]: 2023/10/29 08:29:58 Primary execution client is unavailable (Client claims to have finished syncing, but its last block was from 11h4m58.159221218s ago. It likely doesn't have enough peers), using fallback execution client...
Oct 29 08:29:58 ethpower rocketpoold[39569]: Starting node daemon in Native Mode.
Oct 29 08:29:58 ethpower rocketpoold[39569]: 2023/10/29 08:29:58 Starting metrics exporter on 0.0.0.0:9102.
Oct 29 08:29:59 ethpower rocketpoold[39569]: 2023/10/29 08:29:59 Primary execution client is unavailable (Client claims to have finished syncing, but its last block was from 11h4m59.634280337s ago. It likely doesn't have enough peers), using fallback execution client...
Oct 29 08:29:59 ethpower rocketpoold[39569]: 2023/10/29 08:29:59 Primary consensus client is still syncing (99.99%), using fallback consensus client...
Oct 29 08:30:00 ethpower rocketpoold[39569]: 2023/10/29 08:30:00 Getting network state for EL block 18454657, Beacon slot 7645347
Oct 29 08:30:00 ethpower rocketpoold[39569]: 2023/10/29 08:30:00 1/6 - Retrieved network details (645.828343ms so far)
Oct 29 08:30:01 ethpower rocketpoold[39569]: 2023/10/29 08:30:01 2/6 - Retrieved node details (1.076259573s so far)
Oct 29 08:30:02 ethpower rocketpoold[39569]: 2023/10/29 08:30:02 3/6 - Retrieved minipool details (2.12350685s so far)
Oct 29 08:30:06 ethpower rocketpoold[39569]: 2023/10/29 08:30:06 4/6 - Calculated total effective stake (total time: 6.836885603s)
Oct 29 08:34:42 ethpower rocketpoold[39569]: 2023/10/29 08:34:42 5/6 - Retrieved validator details (total time: 4m42.738185418s)
Oct 29 08:34:42 ethpower rocketpoold[39569]: panic: runtime error: index out of range [4] with length 4
Oct 29 08:34:42 ethpower rocketpoold[39569]: goroutine 167 [running]:
Oct 29 08:34:42 ethpower rocketpoold[39569]: github.com/rocket-pool/smartnode/shared/services/beacon/client.(*StandardHttpClient).getValidatorsByOpts.func1()
Oct 29 08:34:42 ethpower rocketpoold[39569]:         /smartnode/shared/services/beacon/client/std-http-client.go:712 +0x265
Oct 29 08:34:42 ethpower rocketpoold[39569]: golang.org/x/sync/errgroup.(*Group).Go.func1()
Oct 29 08:34:42 ethpower rocketpoold[39569]:         /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
Oct 29 08:34:42 ethpower rocketpoold[39569]: created by golang.org/x/sync/errgroup.(*Group).Go
Oct 29 08:34:42 ethpower rocketpoold[39569]:         /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
Oct 29 08:34:42 ethpower systemd[1]: rp-node.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 29 08:34:42 ethpower systemd[1]: rp-node.service: Failed with result 'exit-code'.
Oct 29 08:34:47 ethpower systemd[1]: rp-node.service: Scheduled restart job, restart counter is at 10.
Oct 29 08:34:47 ethpower systemd[1]: Stopped rp-node.
Oct 29 08:34:47 ethpower systemd[1]: Started rp-node.
...
```

**Comment by 0xfornax** [comment]
Closing as stale. Please let us know if you still have issues.
