### ISSUE TITLE
Don't panic

### ISSUE THREAD

**Issue by xrchz** [rocket-pool/smartnode#584]
`rocketpool version 1.13.6`

```
> rocketpool p s

Your Smart Node is currently using the Ethereum Mainnet.

=== Signalling on Snapshot ===
The node does not currently have a snapshot signalling address set.
To learn more about snapshot signalling, please visit https://docs.rocketpool.net/guides/houston/participate#setting-your-snapshot-signalling-address.
Rocket Pool has 1 Snapshot governance proposal(s) being voted on. You have voted on 1 of those. See details using 'rocketpool network dao-proposals'.

=== Onchain Voting ===
The node <redacted> has NOT been initialized for onchain voting. You need to run `rocketpool pdao initialize-voting` to participate in onchain votes.
The node doesn't have a delegate, which means it can vote directly on onchain proposals after it initializes voting.
The node's local voting power: 0.0000000000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5184d2]

goroutine 1 [running]:
math/big.(*Int).BitLen(...)
        /usr/local/go/src/math/big/int.go:550
math/big.(*Float).SetInt(0xc000614000?, 0xc00073d1f8?)
        /usr/local/go/src/math/big/float.go:604 +0x12
github.com/rocket-pool/rocketpool-go/utils/eth.WeiToEth(0x12bbbe0?)
        /go/pkg/mod/github.com/rocket-pool/rocketpool-go@v1.8.3-0.20240618173422-783b8668f5b4/utils/eth/units.go:18 +0x4b
github.com/rocket-pool/smartnode/rocketpool-cli/pdao.getStatus(0x1a06280?)
        /smartnode/rocketpool-cli/pdao/status.go:123 +0xbc5
github.com/rocket-pool/smartnode/rocketpool-cli/pdao.RegisterCommands.func1(0xc0001c4c60?)
        /smartnode/rocketpool-cli/pdao/commands.go:39 +0x13
github.com/urfave/cli.HandleAction({0xe87ae0?, 0x1172928?}, 0x6?)
        /go/pkg/mod/github.com/urfave/cli@v1.22.12/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0xfe9f99, 0x6}, {0x0, 0x0}, {0xc0005ccea0, 0x1, 0x1}, {0xffc4ac, 0x13}, {0x10003da, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.12/command.go:175 +0x63e
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000170c40, 0xc0001c49a0)
        /go/pkg/mod/github.com/urfave/cli@v1.22.12/app.go:405 +0xe07
github.com/urfave/cli.Command.startApp({{0xfe7c7b, 0x4}, {0x0, 0x0}, {0xc0005cce90, 0x1, 0x1}, {0x1015c10, 0x23}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.12/command.go:380 +0xb58
github.com/urfave/cli.Command.Run({{0xfe7c7b, 0x4}, {0x0, 0x0}, {0xc0005cce90, 0x1, 0x1}, {0x1015c10, 0x23}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.12/command.go:103 +0x7e5
github.com/urfave/cli.(*App).Run(0xc000170a80, {0xc000146000, 0x7, 0x7})
        /go/pkg/mod/github.com/urfave/cli@v1.22.12/app.go:277 +0xb27
main.main()
        /smartnode/rocketpool-cli/rocketpool-cli.go:148 +0xe65
```

**Comment by jshufro** [comment]
@thomaspanf this segfault is here: <https://github.com/rocket-pool/smartnode/blob/v1.13.6/rocketpool-cli/pdao/status.go#L123>

Looks like `response.TotalDelegatedVp` is nil. rocketpool-cli should be nil-safe here, but also we should investigate why the api returned a nil value for this field instead of `big.NewInt(0)`
