### ISSUE TITLE
Could not get minipool status: exit status 2

### ISSUE THREAD

**Issue by kidkal** [rocket-pool/smartnode#61]
The call
`docker exec rocketpool_api /go/bin/rocketpool api minipool status`
returns
```
panic: NewFloat(NaN)

goroutine 354 [running]:
math/big.NewFloat(...)
	/usr/local/go/src/math/big/float.go:90
github.com/rocket-pool/rocketpool-go/utils/eth.GweiToWei(0xfff8000000000000, 0x421dcd6500000000)
	/go/pkg/mod/github.com/rocket-pool/rocketpool-go@v0.0.0-20200813050037-c430afba9ad3/utils/eth/units.go:51 +0x16d
github.com/rocket-pool/smartnode/rocketpool/api/minipool.getMinipoolValidatorDetails(0xc0001841c0, 0x141e560, 0xc0003d2d80, 0xb5ea180dc1a25fec, 0x2a7181e84946a7d1, 0x32d05fa5bb78f58b, 0x1d7f3dacfcce2219, 0x9741068e8befb659, 0x6454a5ee346fcbaf, 0x1b53a0b522860067, ...)
	/src/rocketpool/api/minipool/utils.go:234 +0x2b1
github.com/rocket-pool/smartnode/rocketpool/api/minipool.getMinipoolDetails(0xc0001841c0, 0x141e560, 0xc0003d2d80, 0xb5ea180dc1a25fec, 0x2a7181e84946a7d1, 0xbb78f58b, 0xc000876108, 0x4, 0x8, 0x0, ...)
	/src/rocketpool/api/minipool/utils.go:174 +0x678
github.com/rocket-pool/smartnode/rocketpool/api/minipool.getNodeMinipoolDetails.func6(0x468776, 0x1318058)
	/src/rocketpool/api/minipool/utils.go:100 +0x109
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00032cc30, 0xc000355700)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
```

offending code: 
https://github.com/rocket-pool/smartnode/blob/9090803d5b24483886c1d014540e9883cfc73b97/rocketpool/api/minipool/utils.go#L234

ahem.. it's a... divide by zero

**Comment by moles1** [comment]
Yes, there's a bug in the expected minipool node balance calculation. Should be patched soon, hold tight!

**Comment by moles1** [comment]
Fixed in https://github.com/rocket-pool/smartnode/commit/6cbe7d17be2d823d9f53d1e8d1e497bca83e4dce - code path now returns before the calculation if division by 0 would occur
